// ============================================================
// CONCLAVE — bilingual content + agent data
// ============================================================

window.AGENTS = [
  { id: 'TA',  name: { ru: 'Технический',     en: 'Technical' },     full: { ru: 'Анализ графиков, индикаторы, паттерны',           en: 'Charts, indicators, classic patterns' },           accuracy: 0.71, weight: 0.18, glyph: 'T' },
  { id: 'VOL', name: { ru: 'Объёмный',         en: 'Volume' },        full: { ru: 'Перетоки ликвидности, OBV, кластерный анализ',     en: 'Liquidity flows, OBV, footprint reading' },          accuracy: 0.68, weight: 0.14, glyph: 'V' },
  { id: 'SNT', name: { ru: 'Сентимент',        en: 'Sentiment' },     full: { ru: 'Соцсети, новости, страх и жадность',                en: 'Social, news, fear & greed' },                       accuracy: 0.64, weight: 0.10, glyph: 'S' },
  { id: 'CHN', name: { ru: 'On-Chain',         en: 'On-Chain' },      full: { ru: 'Кошельки китов, ходлеры, активность сети',          en: 'Whale wallets, holders, network activity' },         accuracy: 0.74, weight: 0.16, glyph: 'O' },
  { id: 'PAT', name: { ru: 'Паттерны',         en: 'Pattern' },       full: { ru: 'ML-распознавание формаций и аномалий',              en: 'ML formation & anomaly recognition' },              accuracy: 0.69, weight: 0.13, glyph: 'P' },
  { id: 'MAC', name: { ru: 'Макро',            en: 'Macro' },         full: { ru: 'DXY, доходности, корреляции с традфином',           en: 'DXY, yields, tradfi correlations' },                 accuracy: 0.66, weight: 0.12, glyph: 'M' },
  { id: 'RSK', name: { ru: 'Риск',             en: 'Risk' },          full: { ru: 'Волатильность, ликвидность, размер позиции',        en: 'Volatility, liquidity, position sizing' },           accuracy: 0.78, weight: 0.17, glyph: 'R' },
];

window.VERDICTS = [
  { pair: 'BTC/USDT',  dir: 'LONG',  conf: 84, note: { ru: 'единогласно',          en: 'unanimous' } },
  { pair: 'ETH/USDT',  dir: 'SKIP',  conf: 41, note: { ru: 'разногласие',          en: 'disagreement' } },
  { pair: 'SOL/USDT',  dir: 'SHORT', conf: 71, note: { ru: 'дивергенция объёма',   en: 'volume divergence' } },
  { pair: 'AVAX/USDT', dir: 'LONG',  conf: 68, note: { ru: 'on-chain бычий',       en: 'on-chain bullish' } },
  { pair: 'LINK/USDT', dir: 'SKIP',  conf: 33, note: { ru: 'низкая ликвидность',   en: 'thin liquidity' } },
  { pair: 'ARB/USDT',  dir: 'LONG',  conf: 62, note: { ru: 'паттерн H&S inv.',     en: 'inv. H&S pattern' } },
  { pair: 'DOGE/USDT', dir: 'SHORT', conf: 58, note: { ru: 'сентимент перегрет',   en: 'sentiment overheated' } },
  { pair: 'TIA/USDT',  dir: 'LONG',  conf: 76, note: { ru: 'киты накапливают',     en: 'whales accumulating' } },
];

window.STEPS = [
  {
    n: '01',
    title: { ru: 'Сбор данных', en: 'Ingest' },
    body: {
      ru: 'Котировки, стаканы, on-chain потоки и новости стекаются в единый поток в реальном времени.',
      en: 'Quotes, order books, on-chain flows and news converge into a single real-time stream.',
    },
  },
  {
    n: '02',
    title: { ru: 'Параллельный анализ', en: 'Parallel Analysis' },
    body: {
      ru: 'Семь агентов независимо формируют прогноз — без оглядки друг на друга. Каждый со своей специализацией.',
      en: 'Seven agents independently form a forecast — blind to each other. Each with its specialty.',
    },
  },
  {
    n: '03',
    title: { ru: 'Мета-анализ', en: 'Meta-Analysis' },
    body: {
      ru: 'Супервизор взвешивает голоса по исторической точности агента, силе сигнала и текущему режиму рынка.',
      en: 'The supervisor weighs votes by historical accuracy, signal strength and current market regime.',
    },
  },
  {
    n: '04',
    title: { ru: 'Решение', en: 'Decision' },
    body: {
      ru: 'Long, short или skip — с уровнем уверенности и риск-параметрами. Опционально исполняется автоматически.',
      en: 'Long, short or skip — with confidence and risk parameters. Optionally executed automatically.',
    },
  },
];

window.ADVANTAGES = [
  {
    n: 'I',
    t: { ru: 'Нет одной точки отказа',         en: 'No single point of failure' },
    b: { ru: 'Семь моделей вместо одной — ошибка одного агента редко становится ошибкой совета.',
         en: 'Seven models instead of one — a single agent’s mistake rarely becomes the council’s.' },
  },
  {
    n: 'II',
    t: { ru: 'Фильтр ложных сигналов',          en: 'False-signal filter' },
    b: { ru: 'Если консенсус слабый — система просто не торгует. Skip — это тоже решение.',
         en: 'When consensus is weak, the system simply stays out. Skip is a decision too.' },
  },
  {
    n: 'III',
    t: { ru: 'Адаптивные веса',                  en: 'Adaptive weights' },
    b: { ru: 'Точность каждого агента пересчитывается на скользящем окне — рынок меняется, веса тоже.',
         en: 'Each agent’s accuracy is recomputed on a rolling window — markets shift, weights follow.' },
  },
  {
    n: 'IV',
    t: { ru: 'Прозрачность логики',              en: 'Transparent reasoning' },
    b: { ru: 'Каждое решение — с раскладкой голосов. Видно, кто за, кто против и почему.',
         en: 'Every decision shows its vote breakdown. You see who voted, against, and why.' },
  },
  {
    n: 'V',
    t: { ru: 'Дисциплина без эмоций',            en: 'Discipline without emotion' },
    b: { ru: 'Никакого FOMO, никакой мести рынку. Решает только статистика и риск-лимиты.',
         en: 'No FOMO, no revenge trades. Only statistics and risk limits decide.' },
  },
  {
    n: 'VI',
    t: { ru: 'Риск-менеджмент по умолчанию',     en: 'Risk management by default' },
    b: { ru: 'Размер позиции, стопы и предельная просадка — параметры, а не пожелания.',
         en: 'Position sizing, stops and max drawdown are parameters, not wishes.' },
  },
];

window.STACK = [
  'Multi-Agent LLM',
  'Real-time Market Data',
  'Binance · Bybit · OKX API',
  'Backtesting Engine',
  'Risk Management Layer',
  'WebSocket Stream Fusion',
  'Vector Memory',
  'Rolling Accuracy Tracker',
];

window.ROADMAP = [
  { q: 'Q1 · 2026', s: { ru: 'В работе', en: 'In progress' }, t: { ru: 'MVP с семью агентами',           en: 'MVP with seven agents' },
    b: { ru: 'Закрытое альфа-тестирование на BTC и ETH. Бэктест на 24 месяцах.', en: 'Closed alpha on BTC & ETH. 24-month backtest.' } },
  { q: 'Q2 · 2026', s: { ru: 'Запланировано', en: 'Planned' }, t: { ru: 'Публичная бета',                en: 'Public beta' },
    b: { ru: 'Расширение до топ-30 пар. Дашборд с раскладкой голосов в реальном времени.', en: 'Expansion to top-30 pairs. Live vote-breakdown dashboard.' } },
  { q: 'Q3 · 2026', s: { ru: 'Запланировано', en: 'Planned' }, t: { ru: 'Автоисполнение сделок',         en: 'Auto-execution' },
    b: { ru: 'Подключение к Binance / Bybit / OKX через изолированные API-ключи.', en: 'Binance / Bybit / OKX via isolated API keys.' } },
  { q: 'Q4 · 2026', s: { ru: 'Идея',          en: 'Idea' },     t: { ru: 'Кастомизация агентов',         en: 'Custom agents & marketplace' },
    b: { ru: 'Свои агенты, свои веса. Маркетплейс стратегий между пользователями.', en: 'Bring your own agents and weights. Strategy marketplace.' } },
];

window.FAQ = [
  {
    q: { ru: 'Безопасны ли мои API-ключи?', en: 'Are my API keys safe?' },
    a: { ru: 'Ключи хранятся изолированно на стороне пользователя или в зашифрованном vault, требуют только торговых разрешений (без вывода средств) и могут быть отозваны в любой момент.',
         en: 'Keys are stored isolated client-side or in an encrypted vault, require trade-only permissions (no withdrawals), and can be revoked at any time.' },
  },
  {
    q: { ru: 'Какие биржи поддерживаются?', en: 'Which exchanges are supported?' },
    a: { ru: 'На запуске — Binance, Bybit и OKX. Расширение по запросам сообщества.',
         en: 'At launch — Binance, Bybit and OKX. Expanded by community demand.' },
  },
  {
    q: { ru: 'Сколько это стоит?', en: 'How much does it cost?' },
    a: { ru: 'Подписочная модель с тремя тарифами и пожизненными местами для ранних пользователей. Цены будут опубликованы перед бетой.',
         en: 'Subscription with three tiers and lifetime seats for early users. Pricing will be published before beta.' },
  },
  {
    q: { ru: 'Гарантирует ли система прибыль?', en: 'Does it guarantee profit?' },
    a: { ru: 'Нет. Никто не может гарантировать прибыль на крипторынке. Conclave — это инструмент дисциплины и анализа, а не печатный станок. Прошлые результаты не предсказывают будущих.',
         en: 'No. No one can guarantee profit in crypto. Conclave is a tool for discipline and analysis, not a money printer. Past performance does not predict future results.' },
  },
  {
    q: { ru: 'Как работает риск-менеджмент?', en: 'How does risk management work?' },
    a: { ru: 'Каждая сделка получает размер по правилу Келли с защитной долей, фиксированный стоп и трейлинг. На уровне портфеля — лимит экспозиции, корреляционный фильтр и максимальная просадка.',
         en: 'Each trade is sized by a fractional-Kelly rule with a fixed stop and trailing logic. At the portfolio level — exposure caps, correlation filter, and max-drawdown circuit breaker.' },
  },
];

window.COPY = {
  ru: {
    nav_manifesto: 'Манифест',
    nav_council: 'Совет',
    nav_method: 'Метод',
    nav_dashboard: 'Терминал',
    nav_roadmap: 'План',
    nav_faq: 'Вопросы',
    issue: 'Выпуск №001',
    edition: 'Издание ранних пользователей',
    issued: 'Издаётся ежедневно',
    eyebrow_live: 'СОВЕТ ЗАСЕДАЕТ В РЕАЛЬНОМ ВРЕМЕНИ',
    hero_pre: 'Семь агентов. Один вердикт.',
    hero_h1_a: 'Совет ',
    hero_h1_em: 'ИИ',
    hero_h1_b: ', который не торопится ошибаться.',
    hero_lede: 'Conclave — мульти-агентная система для криптотрейдинга. Семь специализированных моделей голосуют по каждой сделке. Супервизор взвешивает их голоса и решает: long, short или ничего. Особенно — ничего.',
    hero_cta_1: 'Запросить ранний доступ',
    hero_cta_2: 'Смотреть демо',
    stat_agents: 'Агентов в совете',
    stat_signals: 'Сигналов в сутки',
    stat_accuracy: 'Точность на бэктесте',
    stat_skip: 'Решений «skip»',
    problem_eyebrow: 'I · ПРОБЛЕМА',
    problem_h: 'Один ИИ — это одно мнение. На рынке мнений всегда мало.',
    problem_body_1: 'Большинство торговых ботов опирается на одну модель. Когда она ошибается — а ошибается она часто — ошибается всё. Переоптимизация под прошлое, шум вместо сигнала, эмоциональные решения трейдера сверху.',
    problem_body_2: 'Реальные деньги теряются не на сложных рынках, а на ложной уверенности.',
    problem_pull: 'Один взгляд на рынок — это не стратегия. Это суеверие.',
    council_eyebrow: 'II · СОВЕТ',
    council_h: 'Семь специалистов вокруг одного вердикта.',
    council_lede: 'Каждый агент — отдельная модель со своей областью. Они не общаются между собой. Их голоса собирает и взвешивает супервизор — он один видит всю картину.',
    council_legend_long: 'long',
    council_legend_short: 'short',
    council_legend_skip: 'skip',
    method_eyebrow: 'III · МЕТОД',
    method_h: 'Как принимается решение',
    advantages_eyebrow: 'IV · ПРЕИМУЩЕСТВА',
    advantages_h: 'Шесть причин не доверять одной модели.',
    stack_eyebrow: 'V · СТЕК',
    stack_h: 'Что под капотом',
    stack_body: 'Современный мульти-агентный фреймворк, потоковая интеграция с биржами и риск-слой между моделями и реальными деньгами.',
    dash_eyebrow: 'VI · ТЕРМИНАЛ',
    dash_h: 'Заседание в прямом эфире',
    dash_lede: 'Это макет интерфейса. Голоса меняются — система пересчитывает консенсус каждые несколько секунд.',
    roadmap_eyebrow: 'VII · ПЛАН',
    roadmap_h: 'Куда мы идём',
    faq_eyebrow: 'VIII · ВОПРОСЫ',
    faq_h: 'Что нужно знать',
    cta_eyebrow: 'РАННИЙ ДОСТУП',
    cta_h: 'Войдите в первый созыв.',
    cta_body: 'Сто мест в закрытой альфе. Бесплатно для участников до публичного запуска.',
    cta_email: 'Электронная почта',
    cta_tg: 'Telegram (по желанию)',
    cta_btn: 'Присоединиться к waitlist',
    cta_micro: 'Мы пишем редко и по делу. Отписаться — одним кликом.',
    foot_disclaimer_t: 'Дисклеймер о рисках',
    foot_disclaimer: 'Торговля криптовалютами связана с высоким риском и может привести к полной потере вложенных средств. Conclave — аналитический инструмент, а не финансовый совет. Система не гарантирует прибыль. Прошлые результаты не предсказывают будущих. Пользователь несёт полную ответственность за свои торговые решения.',
    foot_links: 'Документация · Whitepaper · Telegram · X · GitHub',
    foot_copy: '© 2026 Conclave Labs. Все права защищены.',
    long: 'LONG', short: 'SHORT', skip: 'SKIP',
    confidence: 'уверенность',
    weight: 'вес',
    accuracy: 'точность',
    verdict: 'Вердикт супервизора',
  },
  en: {
    nav_manifesto: 'Manifesto',
    nav_council: 'Council',
    nav_method: 'Method',
    nav_dashboard: 'Terminal',
    nav_roadmap: 'Roadmap',
    nav_faq: 'FAQ',
    issue: 'Issue №001',
    edition: 'Early-Access Edition',
    issued: 'Published daily',
    eyebrow_live: 'COUNCIL IN SESSION · LIVE',
    hero_pre: 'Seven agents. One verdict.',
    hero_h1_a: 'An ',
    hero_h1_em: 'AI council',
    hero_h1_b: ' that takes its time before it’s wrong.',
    hero_lede: 'Conclave is a multi-agent system for crypto trading. Seven specialised models vote on every trade. A supervisor weighs their votes and decides: long, short, or nothing. Especially — nothing.',
    hero_cta_1: 'Request early access',
    hero_cta_2: 'Watch demo',
    stat_agents: 'Agents in the council',
    stat_signals: 'Signals per day',
    stat_accuracy: 'Accuracy on backtest',
    stat_skip: 'Decisions to skip',
    problem_eyebrow: 'I · THE PROBLEM',
    problem_h: 'One AI is one opinion. The market is short on opinions.',
    problem_body_1: 'Most trading bots lean on a single model. When it’s wrong — and it often is — everything is wrong. Overfitted to the past, noise instead of signal, with the trader’s emotions stacked on top.',
    problem_body_2: 'Real money is lost not on hard markets, but on false certainty.',
    problem_pull: 'One look at the market isn’t a strategy. It’s superstition.',
    council_eyebrow: 'II · COUNCIL',
    council_h: 'Seven specialists around one verdict.',
    council_lede: 'Each agent is a separate model with its own domain. They don’t talk to each other. The supervisor — alone seeing all of them — collects and weighs their votes.',
    council_legend_long: 'long',
    council_legend_short: 'short',
    council_legend_skip: 'skip',
    method_eyebrow: 'III · METHOD',
    method_h: 'How a decision is made',
    advantages_eyebrow: 'IV · ADVANTAGES',
    advantages_h: 'Six reasons not to trust one model.',
    stack_eyebrow: 'V · STACK',
    stack_h: 'Under the hood',
    stack_body: 'A modern multi-agent framework, streaming integrations with exchanges, and a risk layer between the models and real money.',
    dash_eyebrow: 'VI · TERMINAL',
    dash_h: 'Council in session',
    dash_lede: 'This is an interface mock-up. Votes shift — the system recomputes consensus every few seconds.',
    roadmap_eyebrow: 'VII · ROADMAP',
    roadmap_h: 'Where we’re headed',
    faq_eyebrow: 'VIII · QUESTIONS',
    faq_h: 'What you should know',
    cta_eyebrow: 'EARLY ACCESS',
    cta_h: 'Join the first convocation.',
    cta_body: 'A hundred seats in the closed alpha. Free for members until public launch.',
    cta_email: 'Email',
    cta_tg: 'Telegram (optional)',
    cta_btn: 'Join the waitlist',
    cta_micro: 'We write rarely and only when it matters. Unsubscribe in one click.',
    foot_disclaimer_t: 'Risk Disclaimer',
    foot_disclaimer: 'Trading cryptocurrencies carries a high level of risk and can result in the total loss of invested funds. Conclave is an analytical tool, not financial advice. The system does not guarantee profit. Past performance does not predict future results. The user bears full responsibility for their trading decisions.',
    foot_links: 'Docs · Whitepaper · Telegram · X · GitHub',
    foot_copy: '© 2026 Conclave Labs. All rights reserved.',
    long: 'LONG', short: 'SHORT', skip: 'SKIP',
    confidence: 'confidence',
    weight: 'weight',
    accuracy: 'accuracy',
    verdict: 'Supervisor verdict',
  },
};
